export const SELECT_SEQUENCE = 'SELECT_SEQUENCE';
export const SET_CUSTOM_SEQUENCE = 'SET_CUSTOM_SEQUENCE';
export const ADD_ZERO = 'ADD_ZERO';
export const DISPLAY_FEWER_TERMS = 'DISPLAY_FEWER_TERMS';
export const DISPLAY_MORE_TERMS = 'DISPLAY_MORE_TERMS';
export const FETCH_MATRIX = 'FETCH_MATRIX'; 